# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='telefono',
            field=models.PositiveIntegerField(),
        ),
    ]
