# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_cat',
            field=models.ImageField(blank=True, null=True, upload_to='categorias'),
        ),
    ]
