# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_auto_20160901_0522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='nombre',
            new_name='articulo',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='nombre',
            new_name='categoria',
        ),
    ]
