# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0002_auto_20160912_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='descripcion_cat',
            field=models.TextField(max_length=400),
        ),
    ]
