# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-12 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_auto_20160912_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_cat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
