# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0006_auto_20160913_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(max_length=200, unique_for_date='nombre_cat'),
        ),
    ]
