# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0009_auto_20160914_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='contenido',
            field=models.TextField(max_length=100),
        ),
    ]
