# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0010_auto_20160916_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='imagen_art',
            field=models.ImageField(blank=True, null=True, upload_to='articulos'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
