# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0013_auto_20160916_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='derechos',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articulo',
            name='obligaciones',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
