# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0014_auto_20160916_1744'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='contenido',
            new_name='cuerpo_principal',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='articulo',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='imagen_art',
        ),
    ]
