# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0015_auto_20160916_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='descripcion_breve',
            field=models.TextField(default='null', max_length=100),
        ),
    ]
