# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0016_articulo_descripcion_breve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion_breve',
            field=models.TextField(max_length=100),
        ),
    ]
