# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0017_auto_20160916_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='fecha',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
